# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - uses: SwiftyLab/setup-swift@latest
    - name: Build
      run: |
        cd MathUtils.swift
        swift build -v
    - name: Run package executable
      run: |
        cd MathUtils.swift
        swift run
